PointCounter/templates/counter/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get '/help',to: 'static_pages#help'
  get '/about',to: 'static_pages#about'
  get '/contact',to: 'static_pages#contact'
  get '/signup',	to: 'users#new'
  get '/login',		to: 'sessions#new'
  post '/login',	to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'
  post '/signup',	to: 'users#create'
  get  '/ajaxtest' => 'counters#ajaxtest'
  resources :users
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :counters,          only: [:create,:destroy]
end

PointCounter/templates/counter/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/lvyifanlvlv/PointCounter">荧光颗粒计数平台 </a>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于荧光颗粒计数平台",   about_path %></li>
      <li><%= link_to "联系我们", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">新闻</a></li>
    </ul>
  </nav>
</footer>

PointCounter/templates/counter/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "荧光颗粒计数平台", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "主页", root_path %></li>
        <li><%= link_to "帮助", help_path %></li>
        <% if logged_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              账户 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "个人资料", current_user %></li>
              <li><%= link_to "修改个人资料", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "退出登录", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "登录", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

PointCounter/templates/counter/app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

PointCounter/templates/counter/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

PointCounter/templates/counter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default'%>
    <%= render 'layouts/shim'%>

  </head>
  <body style="background: url('/img/bg.jpg') no-repeat;background-size:100%">
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    
    </div>
  </body>
</html>